import { precacheAndRoute, cleanupOutdatedCaches, createHandlerBoundToURL } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';
import { registerRoute, NavigationRoute } from 'workbox-routing';

// Version marker for force-update
const SW_VERSION = '2.1.0';

// Precache all assets generated by Vite
// Ajout de ignoreURLParametersMatching pour ignorer les "?v=2"
precacheAndRoute(self.__WB_MANIFEST, {
    ignoreURLParametersMatching: [/.*/]
});

// Cleanup old caches
cleanupOutdatedCaches();

// Allow headers to take control immediately
clientsClaim();

// Garantit que le rafraîchissement des pages fonctionne hors ligne (SPA)
// Utilise index.html comme fallback pour toutes les routes de navigation
const handler = createHandlerBoundToURL('/index.html');
const navigationRoute = new NavigationRoute(handler);
registerRoute(navigationRoute);

// Force immediate activation removed to allow manual update prompt
// self.addEventListener('install', () => {
//    self.skipWaiting();
// });

// Handle SKIP_WAITING message for user-prompted updates (fallback)
self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});

/**
 * Handle Push Notifications
 */
self.addEventListener('push', (event) => {
    if (!event.data) return;

    try {
        const data = event.data.json();
        const options = {
            body: data.body,
            icon: data.icon || '/pwa-192-v5.png',
            badge: '/badge-72.png',
            vibrate: [100, 50, 100],
            // CRITICAL: Extract url/roomId from ROOT level, not data.data
            data: {
                url: data.url || '/',
                roomId: data.roomId,
                action: data.action,
                invitationId: data.invitationId
            }
        };

        event.waitUntil(
            self.registration.showNotification(data.title || 'Skyjo Score', options)
        );
    } catch (err) {
        console.error('[SW] Push error:', err);
    }
});

/**
 * Handle Notification Clicks
 */
self.addEventListener('notificationclick', (event) => {
    event.notification.close();

    const urlToOpen = event.notification.data?.url || '/';

    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
            // If a window is already open, use postMessage to avoid reload
            for (let i = 0; i < windowClients.length; i++) {
                const client = windowClients[i];
                if (client.url.includes(self.location.origin) && 'focus' in client) {
                    // Send deep-link via postMessage to avoid page reload
                    client.postMessage({ type: 'DEEP_LINK', url: urlToOpen });
                    return client.focus();
                }
            }
            // If no window is open, open a new one
            if (clients.openWindow) {
                return clients.openWindow(urlToOpen);
            }
        })
    );
});