import { precacheAndRoute, cleanupOutdatedCaches, createHandlerBoundToURL } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';
import { registerRoute, NavigationRoute } from 'workbox-routing';

// Version marker
const SW_VERSION = '1.3.3-explicit-update';
console.log(`⚙️ [SW] Service Worker ${SW_VERSION} Loading...`);

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST, {
    ignoreURLParametersMatching: [/.*/]
});

// Cleanup old caches
cleanupOutdatedCaches();

// Claim open clients only after activation. Activation itself remains explicit
// and is triggered by the SKIP_WAITING message below.
clientsClaim();

const handler = createHandlerBoundToURL('/index.html');
const navigationRoute = new NavigationRoute(handler);
registerRoute(navigationRoute);

self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});

/**
 * Robust Push Notification Listener (Natif)
 * Handles FCM Data Messages WITHOUT crashing on undefined properties.
 */
self.addEventListener('push', (event) => {
    console.log('========================================');
    console.log('🔔 [SW] MESSAGE PUSH REÇU');

    let payload = {};
    if (event.data) {
        try {
            payload = event.data.json();
        } catch (e) {
            console.warn('[SW] Erreur parsing JSON:', e);
            payload = { data: { body: event.data.text() } };
        }
    }

    console.log('🔔 Payload brut:', JSON.stringify(payload, null, 2));

    // Extraction des données (Gestion FB/FCM : payload.data ou payload)
    let data = payload.data || payload;

    // Parfois FCM imbrique encore dans data.data
    if (data.data && typeof data.data === 'object' && !data.title) {
        console.log('⚠️ [SW] Données doublées détectées');
        data = data.data;
    }

    console.log('📦 [SW] Données extraites:', data);

    // Sécurisation contre les "undefined" (Cause du crash précédent)
    const title = data.title || '🎮 Skyjo Score';
    const body = data.body || 'Nouvelle notification';
    const roomId = data.roomId || '';
    const invitationId = data.invitationId || '';

    // L'URL cible (/?room= est le standard de l'app)
    const targetUrl = data.url || (roomId ? `/?room=${roomId}` : '/');
    const tag = data.tag || `skyjo-inv-${roomId || 'gen'}-${Date.now()}`;

    console.log('🚀 [SW] URL cible:', targetUrl);

    const options = {
        body: body,
        icon: '/pwa-192-v5.png',
        badge: '/badge-72.png',
        tag: tag,
        data: {
            url: targetUrl,
            roomId: roomId,
            invitationId: invitationId,
            sentAt: data.sentAt,
            tag: tag
        },
        renotify: true,
        requireInteraction: true,
        vibrate: [200, 100, 200],
        sound: '/sounds/notification.mp3'
    };

    console.log('📋 [SW] Affichage notification:', title);
    console.log('========================================');

    event.waitUntil(
        Promise.all([
            self.registration.showNotification(title, options),
            data.sentAt ? fetch('/api/push/track', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    type: 'receive',
                    invitationId: invitationId,
                    sentAt: data.sentAt,
                    receivedAt: Date.now()
                })
            }).catch(e => console.warn('[SW] Erreur track:', e)) : Promise.resolve()
        ])
    );
});

/**
 * Handle Notification Clicks
 */
self.addEventListener('notificationclick', (event) => {
    console.log('========================================');
    console.log('👆 [SW] CLIC SUR NOTIFICATION');

    // Fermer la notification immédiatement
    event.notification.close();

    // Données de la notification
    const data = event.notification.data || {};
    const targetUrl = data.url || '/';

    console.log('👆 Données associées:', data);
    console.log('========================================');
    console.log('🎯 [SW] URL cible:', targetUrl);

    // Stratégie ultra-robuste pour mobile :
    // On tente d'ouvrir ou de recharger immédiatement.
    event.waitUntil(
        self.clients.matchAll({ type: 'window', includeUncontrolled: true })
            .then((clientList) => {
                // Si une fenêtre est déjà là, on tente de la réactiver
                for (let client of clientList) {
                    if (client.url.includes(self.location.origin) && 'focus' in client) {
                        console.log('✅ [SW] Fenêtre trouvée, focus...');
                        return client.focus().then(c => {
                            c.postMessage({ type: 'DEEP_LINK', url: targetUrl });
                            return c;
                        });
                    }
                }

                // Sinon, ou si le focus a échoué, on ouvre une nouvelle fenêtre (le plus fiable sur mobile)
                if (self.clients.openWindow) {
                    const fullUrl = new URL(targetUrl, self.location.origin).href;
                    console.log('🆕 [SW] Ouverture directe:', fullUrl);
                    return self.clients.openWindow(fullUrl);
                }
            })
            .catch(err => {
                console.error('❌ [SW] Erreur de navigation:', err);
                // Dernier recours : tenter au moins d'ouvrir l'accueil
                if (self.clients.openWindow) return self.clients.openWindow('/');
            })
    );
});

self.addEventListener('notificationclose', () => {
    console.log('✖️ [SW] Notification fermée');
});
